### ISSUE TITLE
Invalid response, when 0 custom parameters

### ISSUE THREAD

**Issue by markusheiden** [BingAds/BingAds-Java-SDK#100]
When creating a new (broad match modified) keyword with zero custom parameters (a CustomParameters object with an ArrayOfCustomParameter "parameter" containing an empty list "customParameter") via the BulkServiceManager, the resulting bulk entity is either corrupt or the client lib cannot parse it correctly. The client expects custom parameters to be in the format "{_key}=value". But the server returns "delete_value" in the "Custom Parameter" column.

Stacktrace of bingads client 12.0.3:
```
java.lang.IllegalArgumentException: Bad format for CustomParameters: delete_value
	at com.microsoft.bingads.v12.internal.bulk.StringExtensions.parseCustomParameters(StringExtensions.java:857)
	at com.microsoft.bingads.v12.bulk.entities.BulkKeyword$34.accept(BulkKeyword.java:360)
	at com.microsoft.bingads.v12.bulk.entities.BulkKeyword$34.accept(BulkKeyword.java:356)
	at com.microsoft.bingads.v12.internal.bulk.SingleFieldBulkMapping.convertToEntity(SingleFieldBulkMapping.java:32)
	at com.microsoft.bingads.v12.internal.bulk.SimpleBulkMapping.convertToEntity(SimpleBulkMapping.java:16)
	at com.microsoft.bingads.v12.internal.bulk.MappingHelpers.convertToEntity(MappingHelpers.java:21)
	at com.microsoft.bingads.v12.bulk.entities.BulkKeyword.processMappingsFromRowValues(BulkKeyword.java:428)
	at com.microsoft.bingads.v12.internal.bulk.entities.SingleRecordBulkEntity.readFromRowValues(SingleRecordBulkEntity.java:111)
	at com.microsoft.bingads.v12.internal.bulk.SimpleBulkObjectReader.readNextBulkObject(SimpleBulkObjectReader.java:128)
	at com.microsoft.bingads.v12.internal.bulk.SimpleBulkStreamReader.peek(SimpleBulkStreamReader.java:132)
	at com.microsoft.bingads.v12.internal.bulk.SimpleBulkStreamReader.tryRead(SimpleBulkStreamReader.java:93)
	at com.microsoft.bingads.v12.internal.bulk.SimpleBulkStreamReader.tryRead(SimpleBulkStreamReader.java:74)
	at com.microsoft.bingads.v12.internal.bulk.SimpleBulkStreamReader.read(SimpleBulkStreamReader.java:50)
	at com.microsoft.bingads.v12.internal.bulk.EntityIterator.readNextBatch(EntityIterator.java:54)
	at com.microsoft.bingads.v12.internal.bulk.EntityIterator.updateNextBatch(EntityIterator.java:46)
	at com.microsoft.bingads.v12.internal.bulk.EntityIterator.hasNext(EntityIterator.java:27)
```

**Comment by qitia** [comment]
Thanks for report! I can repro this issue. As workaround, could you please just do not set CustomParameters when there is no content in the list? 

I will work on the fix.

**Comment by markusheiden** [comment]
Yes, I already did that and it works fine.

**Comment by qitia** [comment]
Hi @markusheiden again, we are investigating whether a data fix is needed, could you please help confirm which env are you using? Sandbox or Product? and if you could help send us the tracking id, it would be good!

**Comment by markusheiden** [comment]
This happened with the sandbox. I did not try production yet.

**Comment by markusheiden** [comment]
I tried again today and I hope this is the correct tracking id: e595a6bf-02cf-42b1-b336-807bb8512ce8

**Comment by qitia** [comment]
thanks @markusheiden. So I will close this issue. you can either do not set this CustomParameters  at all as we said above, or you can upgrade the sdk to new version 12.0.4, in which we will handle delete_value more gracefully. You are welcome to reopen this or create new issue in case of any further question.
