### ISSUE TITLE
creating Webpages fails

### ISSUE THREAD

**Issue by schabe77** [BingAds/BingAds-Java-SDK#131]
Hi,

I just switched from lib version 13.0.7.1 to 13.0.13. After the upgrade I'm not able to create Webpages anymore. 
The creation request fails with the error AccountIsNotInPilotForWebpageCriterionWebpageConditionOperatorOrUrlEquals. Doing (almost) the same request with version 13.0.7.1 works without problems.

The only difference between the creation requests is, that with the newer version the WebpageCondition requires an operator. Although `@XmlElement(name = "Operator", nillable = true)` is marked as nillable, a NPE occures when omitting it:
```
Caused by: java.lang.NullPointerException: null
	at com.microsoft.bingads.v13.bulk.entities.WebpageConditionHelper.addRowValuesFromConditions(WebpageConditionHelper.java:21)
	at com.microsoft.bingads.v13.bulk.entities.BulkAdGroupDynamicSearchAdTarget$17.accept(BulkAdGroupDynamicSearchAdTarget.java:231)
	at com.microsoft.bingads.v13.bulk.entities.BulkAdGroupDynamicSearchAdTarget$17.accept(BulkAdGroupDynamicSearchAdTarget.java:223)
	at com.microsoft.bingads.v13.internal.bulk.ComplexBulkMapping.convertToCsv(ComplexBulkMapping.java:45)
	at com.microsoft.bingads.v13.internal.bulk.MappingHelpers.convertToValues(MappingHelpers.java:44)
```

When I use WebpageConditionOperator.EQUALS as operator, I get the mentioned  AccountIsNotInPilotForWebpageCriterionWebpageConditionOperatorOrUrlEquals.

Is this a intended behaviour?

Best regards,

Christian

**Comment by qitia** [comment]
Hi @schabe77

Just confirm I could repro this issue. To workaround, could you please try set the Operator to WebpageConditionOperator.UNKNOWN?

**Comment by schabe77** [comment]
Using WebpageConditionOperator.UNKNOWN works. That was good advice, thank you
