### ISSUE TITLE
IOException: Extra data at the end

### ISSUE THREAD

**Issue by markusheiden** [BingAds/BingAds-Java-SDK#156]
With the recent 13.0.16.2 version, something got wrong. 13.0.16.1 works fine.

```
java.io.IOException: extra data at the end
    at sun.security.util.DerValue.<init>
    at sun.security.util.DerValue.<init>
    at sun.security.provider.certpath.OCSPResponse.<init>
    at sun.security.ssl.CertStatusExtension$OCSPStatusResponse.<init>
    at sun.security.ssl.CertStatusExtension$CertStatusResponseSpec.<init>
    at sun.security.ssl.CertStatusExtension$CTCertStatusResponseConsumer.consume
    at sun.security.ssl.SSLExtension.consumeOnLoad
    at sun.security.ssl.SSLExtensions.consumeOnLoad
    at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate
    at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume
    at sun.security.ssl.SSLHandshake.consume
    at sun.security.ssl.HandshakeContext.dispatch
    at sun.security.ssl.HandshakeContext.dispatch
    at sun.security.ssl.TransportContext.dispatch
    at sun.security.ssl.SSLTransport.decode
    at sun.security.ssl.SSLSocketImpl.decode
    at sun.security.ssl.SSLSocketImpl.readHandshakeRecord
    at sun.security.ssl.SSLSocketImpl.startHandshake
    at sun.security.ssl.SSLSocketImpl.startHandshake
    at sun.net.www.protocol.https.HttpsClient.afterConnect
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream
    at java.net.URL.openStream
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.createReader(RuntimeWSDLParser.java:966)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.resolveWSDL(RuntimeWSDLParser.java:367)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:201)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:179)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:148)
    at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:336)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:293)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:201)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:182)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:178)
    at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:89)
    at jakarta.xml.ws.Service.<init>(Service.java:82)
    at jakarta.xml.ws.Service.create(Service.java:735)
    at com.microsoft.bingads.internal.ServiceFactoryImpl$2.call(ServiceFactoryImpl.java:121)
    at com.microsoft.bingads.internal.ServiceFactoryImpl$2.call(ServiceFactoryImpl.java:115)
    at java.util.concurrent.FutureTask.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker
    at java.util.concurrent.ThreadPoolExecutor$Worker.run
    at java.lang.Thread.run
javax.net.ssl.SSLException: readHandshakeRecord
    at sun.security.ssl.SSLSocketImpl.readHandshakeRecord
    at sun.security.ssl.SSLSocketImpl.startHandshake
    at sun.security.ssl.SSLSocketImpl.startHandshake
    at sun.net.www.protocol.https.HttpsClient.afterConnect
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream
    at java.net.URL.openStream
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.createReader(RuntimeWSDLParser.java:966)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.resolveWSDL(RuntimeWSDLParser.java:367)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:201)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:179)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:148)
    at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:336)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:293)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:201)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:182)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:178)
    at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:89)
    at jakarta.xml.ws.Service.<init>(Service.java:82)
    at jakarta.xml.ws.Service.create(Service.java:735)
    at com.microsoft.bingads.internal.ServiceFactoryImpl$2.call(ServiceFactoryImpl.java:121)
    at com.microsoft.bingads.internal.ServiceFactoryImpl$2.call(ServiceFactoryImpl.java:115)
    at java.util.concurrent.FutureTask.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker
    at java.util.concurrent.ThreadPoolExecutor$Worker.run
    at java.lang.Thread.run
jakarta.xml.ws.WebServiceException: Failed to access the WSDL at: https://reporting.api.bingads.microsoft.com/Api/Advertiser/Reporting/v13/ReportingService.svc?wsdl. It failed with: 
	readHandshakeRecord.
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.tryWithMex(RuntimeWSDLParser.java:235)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:216)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:179)
    at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:148)
    at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:336)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:293)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:201)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:182)
    at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:178)
    at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:89)
    at jakarta.xml.ws.Service.<init>(Service.java:82)
    at jakarta.xml.ws.Service.create(Service.java:735)
    at com.microsoft.bingads.internal.ServiceFactoryImpl$2.call(ServiceFactoryImpl.java:121)
    at com.microsoft.bingads.internal.ServiceFactoryImpl$2.call(ServiceFactoryImpl.java:115)
    at java.util.concurrent.FutureTask.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker
    at java.util.concurrent.ThreadPoolExecutor$Worker.run
    at java.lang.Thread.run
java.util.concurrent.ExecutionException: jakarta.xml.ws.WebServiceException: Failed to access the WSDL at: https://reporting.api.bingads.microsoft.com/Api/Advertiser/Reporting/v13/ReportingService.svc?wsdl. It failed with: 
	readHandshakeRecord.
    at java.util.concurrent.FutureTask.report
    at java.util.concurrent.FutureTask.get
    at com.microsoft.bingads.internal.ServiceFactoryImpl.createServiceWithRetry(ServiceFactoryImpl.java:127)
    at com.microsoft.bingads.internal.ServiceFactoryImpl.createService(ServiceFactoryImpl.java:94)
    at com.microsoft.bingads.ServiceClient.<init>(ServiceClient.java:101)
    at com.microsoft.bingads.v13.reporting.ReportingServiceManager.<init>(ReportingServiceManager.java:80)
    at com.microsoft.bingads.v13.reporting.ReportingServiceManager.<init>(ReportingServiceManager.java:70)
    at com.adsoul.seasupport.features.microsoft.bingads.reporting.BingAdsRetryingReportManager.createReportingServiceManager(BingAdsRetryingReportManager.java:218)
    at com.adsoul.seasupport.features.microsoft.bingads.reporting.BingAdsRetryingReportManager.download(BingAdsRetryingReportManager.java:154)
    at com.adsoul.seasupport.features.microsoft.bingads.reporting.BingAdsRetryingReportManager.lambda$downloadReport$0(BingAdsRetryingReportManager.java:123)
    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
    at com.adsoul.seasupport.features.microsoft.bingads.reporting.BingAdsRetryingReportManager.downloadReport(BingAdsRetryingReportManager.java:121)
    at com.adsoul.seasupport.features.bingads.warehouse.report.bingads.BingAdsKeywordReportServiceImpl.downloadDailyReport(BingAdsKeywordReportServiceImpl.java:163)
    at com.adsoul.seasupport.features.bingads.warehouse.report.bingads.BingAdsKeywordReportWarehouseService.downloadBingAdsKeywordsPerAccount(BingAdsKeywordReportWarehouseService.java:237)
    at com.adsoul.seasupport.features.bingads.warehouse.report.bingads.BingAdsKeywordReportWarehouseService.lambda$downloadAndSaveReports$0(BingAdsKeywordReportWarehouseService.java:163)
    at com.adsoul.redjob.job.pool.Tx.lambda$doCallEach$4(Tx.java:159)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
    at com.adsoul.redjob.job.pool.Tx.lambda$doCallEach$5(Tx.java:159)
    at com.adsoul.seasupport.features.bingads.WithBingAds.lambda$doCallEach$0(WithBingAds.java:66)
    at com.adsoul.seasupport.features.microsoft.bingads.BingAdsSessionHolder.withSessionInternal(BingAdsSessionHolder.java:325)
    at com.adsoul.seasupport.features.microsoft.bingads.BingAdsSessionHolder.withSession(BingAdsSessionHolder.java:264)
    at com.adsoul.seasupport.features.bingads.WithBingAds.lambda$doCallEach$1(WithBingAds.java:65)
    at com.adsoul.redjob.job.pool.IterImpl.lambda$processToMono$2(IterImpl.java:140)
    at com.adsoul.redjob.job.Progress.callWithProgress(Progress.java:79)
    at com.adsoul.redjob.job.Progress.callWithSubProgress(Progress.java:100)
    at com.adsoul.redjob.job.pool.IterImpl.processToMono(IterImpl.java:139)
    at com.adsoul.redjob.job.pool.IterImpl.lambda$doCallEach$0(IterImpl.java:99)
    at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:386)
    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
    at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
    at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
    at java.util.concurrent.FutureTask.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker
    at java.util.concurrent.ThreadPoolExecutor$Worker.run
    at java.lang.Thread.run
com.microsoft.bingads.InternalException: Internal BingAds SDK exception has occured
    at com.microsoft.bingads.internal.ServiceFactoryImpl.createService(ServiceFactoryImpl.java:97)
    at com.microsoft.bingads.ServiceClient.<init>(ServiceClient.java:101)
    at com.microsoft.bingads.v13.reporting.ReportingServiceManager.<init>(ReportingServiceManager.java:80)
    at com.microsoft.bingads.v13.reporting.ReportingServiceManager.<init>(ReportingServiceManager.java:70)
    at com.adsoul.seasupport.features.microsoft.bingads.reporting.BingAdsRetryingReportManager.createReportingServiceManager(BingAdsRetryingReportManager.java:218)
    at com.adsoul.seasupport.features.microsoft.bingads.reporting.BingAdsRetryingReportManager.download(BingAdsRetryingReportManager.java:154)
    at com.adsoul.seasupport.features.microsoft.bingads.reporting.BingAdsRetryingReportManager.lambda$downloadReport$0(BingAdsRetryingReportManager.java:123)
    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
    at com.adsoul.seasupport.features.microsoft.bingads.reporting.BingAdsRetryingReportManager.downloadReport(BingAdsRetryingReportManager.java:121)
    at com.adsoul.seasupport.features.bingads.warehouse.report.bingads.BingAdsKeywordReportServiceImpl.downloadDailyReport(BingAdsKeywordReportServiceImpl.java:163)
    at com.adsoul.seasupport.features.bingads.warehouse.report.bingads.BingAdsKeywordReportWarehouseService.downloadBingAdsKeywordsPerAccount(BingAdsKeywordReportWarehouseService.java:237)
    at com.adsoul.seasupport.features.bingads.warehouse.report.bingads.BingAdsKeywordReportWarehouseService.lambda$downloadAndSaveReports$0(BingAdsKeywordReportWarehouseService.java:163)
    at com.adsoul.redjob.job.pool.Tx.lambda$doCallEach$4(Tx.java:159)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
    at com.adsoul.redjob.job.pool.Tx.lambda$doCallEach$5(Tx.java:159)
    at com.adsoul.seasupport.features.bingads.WithBingAds.lambda$doCallEach$0(WithBingAds.java:66)
    at com.adsoul.seasupport.features.microsoft.bingads.BingAdsSessionHolder.withSessionInternal(BingAdsSessionHolder.java:325)
    at com.adsoul.seasupport.features.microsoft.bingads.BingAdsSessionHolder.withSession(BingAdsSessionHolder.java:264)
    at com.adsoul.seasupport.features.bingads.WithBingAds.lambda$doCallEach$1(WithBingAds.java:65)
    at com.adsoul.redjob.job.pool.IterImpl.lambda$processToMono$2(IterImpl.java:140)
    at com.adsoul.redjob.job.Progress.callWithProgress(Progress.java:79)
    at com.adsoul.redjob.job.Progress.callWithSubProgress(Progress.java:100)
    at com.adsoul.redjob.job.pool.IterImpl.processToMono(IterImpl.java:139)
    at com.adsoul.redjob.job.pool.IterImpl.lambda$doCallEach$0(IterImpl.java:99)
    at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:386)
    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
    at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
    at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
    at java.util.concurrent.FutureTask.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker
    at java.util.concurrent.ThreadPoolExecutor$Worker.run
    at java.lang.Thread.run
```

**Comment by markusheiden** [comment]
For the prior version 13.0.16.1 `com.sun.xml.ws:jaxws-rt` was needed in the classpath to make it work.
That was causing the above problems with the current version 13.0.16.2.
Simply removing `com.sun.xml.ws:jaxws-rt` seems to fix the problem.

It would be nice if such a breaking change results in (at least) a minor version (second number) increase in the future.

**Comment by markusheiden** [comment]
I was wrong, the above exception still persists even when reverting to version 13.0.16.1.

**Comment by markusheiden** [comment]
It looks like the recent JDK 20.0.2 introduced this issue.

**Comment by markusheiden** [comment]
We first noticed the problem around 2023-07-25 21 o'clock MESZ.

**Comment by schabe77** [comment]
I also think it's a misconfiguration on server side. We experienced this problem the first time on 2023-05-23, then later on 2023-06-01, 2023-06-27 and 2023-06-28. The problem always disappeared after a while, but since yesterday there are much more errors than before.

The problem is not related to the API Software - it already occurs on connection establishment. And it happens with jdk11 and jdk17.

I sent the (probably) problematic certificate to our contact persons at microsoft already in May (but it seems they didn't know what to do with it). so i post it here again (taken from running java-app with ssl-debug property). THe problem seems to be the    "extra data at the end" at the "extensions" / "status_request (5)" part:

```
  {
    "certificate" : {
      "version"            : "v3",
      "serial number"      : "33009D94DEF2F5C95B0CC0A6D10000009D94DE",
      "signature algorithm": "SHA384withRSA",
      "issuer"             : "CN=Microsoft Azure TLS Issuing CA 02, O=Microsoft Corporation, C=US",
      "not before"         : "2023-03-18 15:08:21.000 CET",
      "not  after"         : "2024-03-12 15:08:21.000 CET",
      "subject"            : "CN=bingads.microsoft.com, O=Microsoft Corporation, L=Redmond, ST=WA, C=US",
      "subject public key" : "RSA",
      "extensions"         : [
        {
          ObjectId: 1.3.6.1.4.1.11129.2.4.2 Criticality=false
        },
        {
          ObjectId: 1.3.6.1.4.1.311.21.10 Criticality=false
        },
        {
          ObjectId: 1.3.6.1.4.1.311.21.7 Criticality=false
        },
        {
          ObjectId: 1.3.6.1.5.5.7.1.1 Criticality=false
          AuthorityInfoAccess [
            [
             accessMethod: caIssuers
             accessLocation: URIName: http://www.microsoft.com/pkiops/certs/Microsoft%20Azure%20TLS%20Issuing%20CA%2002%20-%20xsign.crt
          , 
             accessMethod: ocsp
             accessLocation: URIName: http://oneocsp.microsoft.com/ocsp
          ]
          ]
        },
        {
          ObjectId: 2.5.29.35 Criticality=false
          AuthorityKeyIdentifier [
          KeyIdentifier [
          0000: 00 AB 91 FC 21 62 26 97   9A A8 79 1B 61 41 90 60  ....!b&...y.aA.`
          0010: A9 62 67 FD                                        .bg.
          ]
          ]
        },
        {
          ObjectId: 2.5.29.19 Criticality=true
          BasicConstraints:[
            CA:false
            PathLen: undefined
          ]
        },
        {
          ObjectId: 2.5.29.31 Criticality=false
          CRLDistributionPoints [
            [DistributionPoint:
               [URIName: http://www.microsoft.com/pkiops/crl/Microsoft%20Azure%20TLS%20Issuing%20CA%2002.crl]
          ]]
        },
        {
          ObjectId: 2.5.29.32 Criticality=false
          CertificatePolicies [
            [CertificatePolicyId: [1.3.6.1.4.1.311.76.509.1.1]
          [PolicyQualifierInfo: [
            qualifierID: 1.3.6.1.5.5.7.2.1
            qualifier: 0000: 16 33 68 74 74 70 3A 2F   2F 77 77 77 2E 6D 69 63  .3http://www.mic
          0010: 72 6F 73 6F 66 74 2E 63   6F 6D 2F 70 6B 69 6F 70  rosoft.com/pkiop
          0020: 73 2F 44 6F 63 73 2F 52   65 70 6F 73 69 74 6F 72  s/Docs/Repositor
          0030: 79 2E 68 74 6D                                     y.htm
          
          ]]  ]
            [CertificatePolicyId: [2.23.140.1.2.2]
          []  ]
          ]
        },
        {
          ObjectId: 2.5.29.37 Criticality=false
          ExtendedKeyUsages [
            clientAuth
            serverAuth
          ]
        },
        {
          ObjectId: 2.5.29.15 Criticality=true
          KeyUsage [
            DigitalSignature
            Key_Encipherment
            Data_Encipherment
          ]
        },
        {
          ObjectId: 2.5.29.17 Criticality=false
          SubjectAlternativeName [
            DNSName: bingads.microsoft.com
            DNSName: api.bingads.microsoft.com
            DNSName: *.bingads.microsoft.com
            DNSName: *.api.bingads.microsoft.com
            DNSName: *.partner.api.bingads.microsoft.com
          ]
        },
        {
          ObjectId: 2.5.29.14 Criticality=false
          SubjectKeyIdentifier [
          KeyIdentifier [
          0000: 76 09 AA 6F F7 18 12 86   39 01 11 23 36 F9 D8 A1  v..o....9..#6...
          0010: 85 20 EA 7D                                        . ..
          ]
          ]
        }
      ]}
    "extensions": {
      "status_request (5)": {
        extra data at the end
      }
    }
  }
```

**Comment by markusheiden** [comment]
You are right. I found these errors for 2023-06-27 and 2023-06-28 too. But in that time frame, they happened significantly less.

**Comment by qitia** [comment]
yes this is a service side issue. It should have been fixed, when you see this kinds of exception, please reach out to support team adpodapi@microsoft.com
