### ISSUE TITLE
Could not initialize class org.apache.cxf.attachment.AttachmentUtil

### ISSUE THREAD

**Issue by NicholasLD** [BingAds/BingAds-Java-SDK#193]
my environment:
JDK Temurin-21.0.3+9
SpringBoot 3.1.7
BingAds SDK Version: 13.0.20

This problem only occurs in the production environment

`
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: Could not initialize class org.apache.cxf.attachment.AttachmentUtil
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.cxf.attachment.AttachmentUtil
        at org.apache.cxf.interceptor.AttachmentOutInterceptor.handleMessage(AttachmentOutInterceptor.java:66)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:528)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:439)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:354)
        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:312)
        at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
        at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:140)
        at jdk.proxy2/jdk.proxy2.$Proxy294.searchInsertionOrders(Unknown Source)
        at org.dromara.ads.bing.BingBillingService.searchInsertionOrders(BingBillingService.java:37)
        at org.dromara.ads.job.FetchTodayPerformanceProcessor.lambda$process$5(FetchTodayPerformanceProcessor.java:68)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        ... 3 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: Provider for jakarta.activation.spi.MailcapRegistryProvider cannot be found [in thread "pool-9-thread-10"]
        at jakarta.activation.FactoryFinder.find(FactoryFinder.java:95)
        at jakarta.activation.MailcapCommandMap.getImplementation(MailcapCommandMap.java:705)
        at jakarta.activation.MailcapCommandMap.loadFile(MailcapCommandMap.java:284)
        at jakarta.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:154)
        at jakarta.activation.CommandMap.getDefaultCommandMap(CommandMap.java:60)
        at org.apache.cxf.attachment.AttachmentUtil.<clinit>(AttachmentUtil.java:85)
        ... 15 common frames omitted
`

**Comment by wjwLyoko** [comment]
Excuse me, have you solved the problem, I reported this error when I was unfamiliar

**Comment by NicholasLD** [comment]
> Excuse me, have you solved the problem, I reported this error when I was unfamiliar

并没有完全解决，我认为是必应SDK的BUG，我在拉取报告时取消使用了线程池，暂时解决了这个问题

**Comment by NicholasLD** [comment]
@wjwLyoko 能否留个联系方式
