### ISSUE TITLE
Please update CXF

### ISSUE THREAD

**Issue by markusheiden** [BingAds/BingAds-Java-SDK#95]
I have problems with JDK11 and the rather old cxf dependency of Bing Ads. May you please update it to a more recent version?

java.lang.NoSuchMethodError: org.codehaus.stax2.ri.EmptyIterator.getInstance()Lorg/codehaus/stax2/ri/EmptyIterator;
	at com.ctc.wstx.sw.OutputElementBase.getPrefixes(OutputElementBase.java:358) ~[woodstox-core-asl-4.4.1.jar!/:4.4.1]
	at org.apache.cxf.staxutils.StaxUtils.writeStartElement(StaxUtils.java:813) ~[cxf-core-3.0.15.jar!/:3.0.15]
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:760) ~[cxf-core-3.0.15.jar!/:3.0.15]
	at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:724) ~[cxf-core-3.0.15.jar!/:3.0.15]
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:214) ~[cxf-rt-bindings-soap-3.0.15.jar!/:3.0.15]
	at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174) ~[cxf-rt-bindings-soap-3.0.15.jar!/:3.0.15]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[cxf-core-3.0.15.jar!/:3.0.15]
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:520) ~[cxf-core-3.0.15.jar!/:3.0.15]
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:429) ~[cxf-core-3.0.15.jar!/:3.0.15]
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:330) ~[cxf-core-3.0.15.jar!/:3.0.15]
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:283) ~[cxf-core-3.0.15.jar!/:3.0.15]
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96) ~[cxf-rt-frontend-simple-3.0.15.jar!/:3.0.15]
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:138) ~[cxf-rt-frontend-jaxws-3.0.15.jar!/:3.0.15]
	at com.sun.proxy.$Proxy344.getAccountsInfo(Unknown Source) ~[?:?]

**Comment by qitia** [comment]
Hi @markusheiden thanks for reach out. I will evaluate and come back.

**Comment by qitia** [comment]
Cxf version has been upgraded from 3.0.15 to 3.2.7
